name: Automated FB Queue

on:
  schedule:
    - cron: '0 1,9,17 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Python & Dependencies
        run: |
          pip install google-genai huggingface_hub[inference] pillow python-dotenv requests

      - name: Run Post Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python main.py

      - name: Commit Changes to JSON
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add topics.json
          git commit -m "Update queue: Mark topic as posted" || echo "No changes to commit"
          git push